import pathlib

MIN_INTENSITY_PER_CONTROL_CHANNEL = 5000
STANDARD_DEVIATION_FILTER_THRESHOLD = 0.5
MIN_NUM_UNIQUE_SEQUENCES = 2
MIN_NUM_DATASETS = 2
DYNAMIC_FOLD_CHANGE_THRESHOLD = 3
CHASE_FOLD_CHANGE_THRESHOLD = 2
HYDROXYLAMINE_REDUCTION_THRESHOLD = 50
DATA_OUTPUT_PATH = pathlib.Path('output')
DATA_INPUT_PATH = pathlib.Path('input')
FIG_OUTPUT_PATH = pathlib.Path('plots')
UNIPROT_SEARCH_DB_PATH = DATA_INPUT_PATH.joinpath('20181024_human_reviewed_uniprot_GFP_NRAS.fasta')
CACHE_DIR = pathlib.Path('.cache')
